# Generated by Django 3.2.3 on 2022-09-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
